# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        architecture: x64
        python-version: 3.8
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: adopt
    - name: Build with Maven
      run: |
        mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -e --settings .mvn/custom-settings.xml
        mvn test -B --settings .mvn/custom-settings.xml
    - name: Build Python package
      run: python setup.py sdist
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: prokaryote-2.4.5.tar.gz
        path: dist/
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*tar.gz

    
    
